### ISSUE TITLE
Bind() Error

### ISSUE THREAD

**Issue by 0xastro** [ericps1/crts#14]
I started the `crts_controller` to initiate a scenario, then I stop/terminate the controller manually using ctr+z. Then I try to recreate the socket connection(start `crts_controller` again) but I got the following error. `ERROR: bind() error`. So I have to re-establish my ssh again to the server.

**Comment by ericps1** [comment]
Hi, ctr+z doesn't terminate a process, it puts it in the background. If you run ($ top) after ctr+z, you would still see crts_controller running. Since the process is still running, the socket is still bound and you cannot start a new process that binds to it. Logging out of your SSH session terminates all processes including those in the background, so when you log back in you're able to start crts_controller again. To terminate the process you want ctr+c.
